export default {
    JWT_ADMIN_SECRET: "jil1865q5wa",
    JWT_USER_SECRET: "jil1865q5w",
    JWT_REF_ADMIN_SECRET : "iloveindia",
    API_VERSION: "v1",
    ADMIN_EXPIRY_IN_MINUTES: 1440,
    ADMIN_PASSWORD_ATTEMPTS: 3
}